package database

import "database/sql"

func RunMigrations(db *sql.DB) error {
	if err := db.Ping(); err != nil {
		return err
	}

	statements := []string{
		`create table if not exists tenants (
			id uuid primary key,
			name text not null,
			slug text not null unique,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)`,
		`create table if not exists users (
			id uuid primary key,
			tenant_id uuid null references tenants(id) on delete set null,
			supabase_user_id uuid null unique,
			email text not null unique,
			name text not null,
			role text not null default 'owner',
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)`,
		`create table if not exists events (
			id uuid primary key,
			tenant_id uuid not null references tenants(id) on delete cascade,
			title text not null,
			description text not null default '',
			starts_at timestamptz not null,
			ends_at timestamptz null,
			location text not null default '',
			slug text not null,
			status text not null default 'draft',
			timezone text not null default 'America/Sao_Paulo',
			hero json not null default '{}'::json,
			content json not null default '{}'::json,
			theme json not null default '{}'::json,
			gallery json,
			seo json,
			template_id text not null default '',
			image text not null default '',
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			unique (tenant_id, slug)
		)`,
		`create table if not exists guests (
			id uuid primary key,
			event_id uuid not null references events(id) on delete cascade,
			name text not null,
			email text not null,
			phone text not null default '',
			status text not null default 'invited',
			party_size integer not null default 1,
			max_companions integer not null default 5,
			invite_token text not null default '',
			metadata jsonb not null default '{}'::jsonb,
			last_seen_at timestamptz,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			unique (event_id, email)
		)`,
		`create table if not exists rsvps (
			id uuid primary key,
			guest_id uuid not null references guests(id) on delete cascade,
			event_id uuid not null references events(id) on delete cascade,
			status text not null,
			companions integer not null default 0,
			message text not null default '',
			source text not null default '',
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			unique (guest_id)
		)`,
		`create table if not exists event_budget_items (
			id uuid primary key,
			event_id uuid not null references events(id) on delete cascade,
			description text not null,
			category text not null default '',
			amount double precision not null default 0,
			paid boolean not null default false,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)`,
		`create table if not exists event_gifts (
			id uuid primary key,
			event_id uuid not null references events(id) on delete cascade,
			name text not null,
			description text not null default '',
			price double precision not null default 0,
			url text not null default '',
			reserved boolean not null default false,
			reserved_by text not null default '',
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)`,
		`create table if not exists event_reminder_campaigns (
			id uuid primary key,
			event_id uuid not null references events(id) on delete cascade,
			from_email text not null,
			recipients json not null default '[]'::json,
			recipient_count integer not null default 0,
			subject text not null,
			message text not null,
			status text not null default 'queued',
			provider_message_id text not null default '',
			error_message text not null default '',
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)`,
		`create table if not exists public_event_cache (
			event_id uuid primary key references events(id) on delete cascade,
			payload jsonb not null default '{}'::jsonb,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now()
		)`,
		`alter table events add column if not exists tenant_id uuid`,
		`alter table events add column if not exists name text`,
		`alter table events add column if not exists title text`,
		`alter table events add column if not exists description text not null default ''`,
		`alter table events add column if not exists status text not null default 'draft'`,
		`alter table events add column if not exists timezone text not null default 'America/Sao_Paulo'`,
		`alter table events add column if not exists starts_at timestamptz`,
		`alter table events add column if not exists ends_at timestamptz`,
		`alter table events add column if not exists location text not null default ''`,
		`alter table events add column if not exists venue_name text`,
		`alter table events add column if not exists address text`,
		`alter table events add column if not exists spotify_playlist_url text`,
		`alter table events add column if not exists hero json not null default '{}'::json`,
		`alter table events add column if not exists content json not null default '{}'::json`,
		`alter table events add column if not exists theme json not null default '{}'::json`,
		`alter table events add column if not exists gallery json`,
		`alter table events add column if not exists seo json`,
		`alter table events add column if not exists capacity integer`,
		`alter table events add column if not exists template_id text not null default ''`,
		`alter table events add column if not exists image text not null default ''`,
		`alter table events add column if not exists slug text`,
		`alter table events add column if not exists created_at timestamptz not null default now()`,
		`alter table events add column if not exists updated_at timestamptz not null default now()`,
		`alter table guests add column if not exists event_id uuid`,
		`alter table guests add column if not exists name text`,
		`alter table guests add column if not exists email text`,
		`alter table guests add column if not exists phone text not null default ''`,
		`alter table guests add column if not exists status text not null default 'invited'`,
		`alter table guests add column if not exists party_size integer not null default 1`,
		`alter table guests add column if not exists max_companions integer not null default 5`,
		`alter table guests add column if not exists invite_token text not null default ''`,
		`alter table guests add column if not exists metadata jsonb not null default '{}'::jsonb`,
		`alter table guests add column if not exists last_seen_at timestamptz`,
		`alter table guests add column if not exists created_at timestamptz not null default now()`,
		`alter table guests add column if not exists updated_at timestamptz not null default now()`,
		`alter table rsvps add column if not exists guest_id uuid`,
		`alter table rsvps add column if not exists event_id uuid`,
		`alter table rsvps add column if not exists status text`,
		`alter table rsvps add column if not exists companions integer not null default 0`,
		`alter table rsvps add column if not exists message text not null default ''`,
		`alter table rsvps add column if not exists source text not null default ''`,
		`alter table rsvps add column if not exists created_at timestamptz not null default now()`,
		`alter table rsvps add column if not exists updated_at timestamptz not null default now()`,
		`create unique index if not exists guests_event_invite_token_idx on guests(event_id, invite_token) where invite_token <> ''`,
		`alter table event_budget_items add column if not exists event_id uuid`,
		`alter table event_budget_items add column if not exists description text`,
		`alter table event_budget_items add column if not exists category text not null default ''`,
		`alter table event_budget_items add column if not exists amount double precision not null default 0`,
		`alter table event_budget_items add column if not exists paid boolean not null default false`,
		`alter table event_budget_items add column if not exists created_at timestamptz not null default now()`,
		`alter table event_budget_items add column if not exists updated_at timestamptz not null default now()`,
		`alter table event_gifts add column if not exists event_id uuid`,
		`alter table event_gifts add column if not exists name text`,
		`alter table event_gifts add column if not exists description text not null default ''`,
		`alter table event_gifts add column if not exists price double precision not null default 0`,
		`alter table event_gifts add column if not exists url text not null default ''`,
		`alter table event_gifts add column if not exists reserved boolean not null default false`,
		`alter table event_gifts add column if not exists reserved_by text not null default ''`,
		`alter table event_gifts add column if not exists created_at timestamptz not null default now()`,
		`alter table event_gifts add column if not exists updated_at timestamptz not null default now()`,
		`alter table event_reminder_campaigns add column if not exists event_id uuid`,
		`alter table event_reminder_campaigns add column if not exists from_email text`,
		`alter table event_reminder_campaigns add column if not exists recipients json not null default '[]'::json`,
		`alter table event_reminder_campaigns add column if not exists recipient_count integer not null default 0`,
		`alter table event_reminder_campaigns add column if not exists subject text`,
		`alter table event_reminder_campaigns add column if not exists message text`,
		`alter table event_reminder_campaigns add column if not exists status text not null default 'queued'`,
		`alter table event_reminder_campaigns add column if not exists provider_message_id text not null default ''`,
		`alter table event_reminder_campaigns add column if not exists error_message text not null default ''`,
		`alter table event_reminder_campaigns add column if not exists created_at timestamptz not null default now()`,
		`alter table event_reminder_campaigns add column if not exists updated_at timestamptz not null default now()`,
		`alter table public_event_cache add column if not exists event_id uuid`,
		`alter table public_event_cache add column if not exists payload jsonb not null default '{}'::jsonb`,
		`alter table public_event_cache add column if not exists created_at timestamptz not null default now()`,
		`alter table public_event_cache add column if not exists updated_at timestamptz not null default now()`,
	}

	for _, statement := range statements {
		if _, err := db.Exec(statement); err != nil {
			return err
		}
	}

	return nil
}
